name: Feature Request
description: Propose an implementation feature
title: "[Feature]: "
labels:
  - enhancement

body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem would this feature solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: Describe the proposed solution.
    validations:
      required: true

  - type: textarea
    id: compatibility
    attributes:
      label: Compatibility
      description: Explain potential protocol or implementation compatibility implications.
